
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luizt
 */
public class Exercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio4
     */
    public Exercicio4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMenu = new javax.swing.JLabel();
        boxCoca = new javax.swing.JCheckBox();
        boxFanta = new javax.swing.JCheckBox();
        boxSalada = new javax.swing.JCheckBox();
        boxTudo = new javax.swing.JCheckBox();
        boxBatataFrita = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbMenu.setText("Cardápio");

        boxCoca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxCoca.setText("Coca - 5.00");

        boxFanta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxFanta.setText("Fanta - 4.00");

        boxSalada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxSalada.setText("X - Salada - 10.00");

        boxTudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxTudo.setText("X - Tudo - 16.00");

        boxBatataFrita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxBatataFrita.setText("Batata frita - 8.00");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxBatataFrita)
                    .addComponent(boxTudo)
                    .addComponent(boxSalada)
                    .addComponent(lbMenu)
                    .addComponent(boxCoca)
                    .addComponent(boxFanta))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMenu)
                .addGap(18, 18, 18)
                .addComponent(boxCoca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxFanta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSalada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxTudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxBatataFrita)
                .addGap(26, 26, 26)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        boolean coca = boxCoca.isSelected();
        boolean fanta = boxFanta.isSelected();
        boolean salada = boxSalada.isSelected();
        boolean tudo = boxTudo.isSelected();
        boolean batatafrita = boxBatataFrita.isSelected();
        double resultado = 0;
        
        if(coca == true){
            resultado = resultado + 5;
        }
        if(fanta == true){
            resultado = resultado + 4;
        }
        if(salada == true){
            resultado = resultado + 10;
        }
        if(tudo == true){
            resultado = resultado + 16;
        }
        if(batatafrita == true){
            resultado = resultado + 8;
        }
        if(resultado > 0){
            JOptionPane.showMessageDialog(null, "O valor total da compra será: R$ " + resultado);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não selecionou nenhum produto.");
        }
               
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxBatataFrita;
    private javax.swing.JCheckBox boxCoca;
    private javax.swing.JCheckBox boxFanta;
    private javax.swing.JCheckBox boxSalada;
    private javax.swing.JCheckBox boxTudo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lbMenu;
    // End of variables declaration//GEN-END:variables
}
