
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Exercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio1
     */
    public Exercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupDesconto = new javax.swing.ButtonGroup();
        lbPreço = new javax.swing.JLabel();
        txValor = new javax.swing.JTextField();
        lbDesconto = new javax.swing.JLabel();
        radDez = new javax.swing.JRadioButton();
        radVinte = new javax.swing.JRadioButton();
        radTrinta = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPreço.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPreço.setText("Preço:");

        txValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbDesconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDesconto.setText("Desconto:");

        groupDesconto.add(radDez);
        radDez.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radDez.setSelected(true);
        radDez.setText("10%");

        groupDesconto.add(radVinte);
        radVinte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radVinte.setText("20%");

        groupDesconto.add(radTrinta);
        radTrinta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radTrinta.setText("30%");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radVinte)
                            .addComponent(radDez)
                            .addComponent(radTrinta)
                            .addComponent(btnCalcular)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPreço)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreço)
                    .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDesconto)
                    .addComponent(radDez))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radVinte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radTrinta)
                .addGap(67, 67, 67)
                .addComponent(btnCalcular)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        float preco = Float.parseFloat(txValor.getText());
        boolean Dez = radDez.isSelected();
        boolean Vinte = radVinte.isSelected();
        boolean Trinta = radTrinta.isSelected();
        double resultado;
        
        if(Dez == true){
            resultado = preco*0.9;
            JOptionPane.showMessageDialog(null, "Valor com 10% de desconto será: " + resultado);
        }
        
        if(Vinte == true){
            resultado = preco*0.8;
            JOptionPane.showMessageDialog(null, "Valor com 20% de desconto será: " + resultado);
        }
        
        if(Trinta == true){
            resultado = preco*0.7;
            JOptionPane.showMessageDialog(null, "Valor com 30% de desconto será: " + resultado);
        }           
        
        
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Exercicio1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup groupDesconto;
    private javax.swing.JLabel lbDesconto;
    private javax.swing.JLabel lbPreço;
    private javax.swing.JRadioButton radDez;
    private javax.swing.JRadioButton radTrinta;
    private javax.swing.JRadioButton radVinte;
    private javax.swing.JTextField txValor;
    // End of variables declaration//GEN-END:variables
}
