
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luizt
 */
public class Exercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio3
     */
    public Exercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupOpMatematico = new javax.swing.ButtonGroup();
        txtPrimeiroN = new javax.swing.JTextField();
        txtSegundoN = new javax.swing.JTextField();
        radMais = new javax.swing.JRadioButton();
        radMenos = new javax.swing.JRadioButton();
        radMultiplica = new javax.swing.JRadioButton();
        radDivide = new javax.swing.JRadioButton();
        lbOperacao = new javax.swing.JLabel();
        btnCalcula = new javax.swing.JButton();
        lbPrimeiroN = new javax.swing.JLabel();
        lbSegundoN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        groupOpMatematico.add(radMais);
        radMais.setSelected(true);
        radMais.setText("+");

        groupOpMatematico.add(radMenos);
        radMenos.setText("-");

        groupOpMatematico.add(radMultiplica);
        radMultiplica.setText("*");

        groupOpMatematico.add(radDivide);
        radDivide.setText("/");

        lbOperacao.setText("Operação:");

        btnCalcula.setText("Calcular");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });

        lbPrimeiroN.setText("Primeiro Número:");

        lbSegundoN.setText("Segundo Número:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbSegundoN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPrimeiroN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbOperacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radMais)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radMultiplica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radDivide))
                            .addComponent(txtPrimeiroN)
                            .addComponent(txtSegundoN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrimeiroN)
                    .addComponent(txtPrimeiroN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSegundoN)
                    .addComponent(txtSegundoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOperacao)
                    .addComponent(radMais)
                    .addComponent(radMenos)
                    .addComponent(radMultiplica)
                    .addComponent(radDivide))
                .addGap(18, 18, 18)
                .addComponent(btnCalcula)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        double valorum = Double.parseDouble(txtPrimeiroN.getText());
        double valordois = Double.parseDouble(txtSegundoN.getText());
        boolean somar = radMais.isSelected();
        boolean subtrair = radMenos.isSelected();
        boolean multiplicar = radMultiplica.isSelected();
        boolean dividir = radDivide.isSelected();
        double resultado;

        if(somar == true){
            resultado=valorum+valordois;
            JOptionPane.showMessageDialog(null,"A adição será: " + resultado);
        }
        else{
            if(subtrair == true){
                resultado=valorum-valordois;
                JOptionPane.showMessageDialog(null,"A subtração será: " + resultado);
            }
            else{
                if(multiplicar == true){
                    resultado=valorum*valordois;
                    JOptionPane.showMessageDialog(null,"A multiplicação será: " + resultado);
                }
                else{
                    resultado=valorum/valordois;
                    JOptionPane.showMessageDialog(null,"A divisão será: " + resultado);
                }
            }
        }

    }//GEN-LAST:event_btnCalculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcula;
    private javax.swing.ButtonGroup groupOpMatematico;
    private javax.swing.JLabel lbOperacao;
    private javax.swing.JLabel lbPrimeiroN;
    private javax.swing.JLabel lbSegundoN;
    private javax.swing.JRadioButton radDivide;
    private javax.swing.JRadioButton radMais;
    private javax.swing.JRadioButton radMenos;
    private javax.swing.JRadioButton radMultiplica;
    private javax.swing.JTextField txtPrimeiroN;
    private javax.swing.JTextField txtSegundoN;
    // End of variables declaration//GEN-END:variables
}
