
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luizt
 */
public class Exercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercicio2
     */
    public Exercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupMoeda = new javax.swing.ButtonGroup();
        lbValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lbMoeda = new javax.swing.JLabel();
        togDolar = new javax.swing.JToggleButton();
        togEuro = new javax.swing.JToggleButton();
        togLibra = new javax.swing.JToggleButton();
        btnConverter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbValor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbValor.setText("Valor:");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbMoeda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMoeda.setText("Moeda:");

        groupMoeda.add(togDolar);
        togDolar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        togDolar.setSelected(true);
        togDolar.setText("Dolar - R$ 3,00");

        groupMoeda.add(togEuro);
        togEuro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        togEuro.setText("Euro - R$ 4,00");

        groupMoeda.add(togLibra);
        togLibra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        togLibra.setText("Libra - R$ 5,00");

        btnConverter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConverter.setText("Converter");
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMoeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(togDolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(togEuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(togLibra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnConverter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbValor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMoeda)
                    .addComponent(togDolar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(togEuro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(togLibra)
                .addGap(28, 28, 28)
                .addComponent(btnConverter)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        
        double moeda = Double.parseDouble(txtValor.getText());
        boolean dolar = togDolar.isSelected();
        boolean euro = togEuro.isSelected();
        boolean libra = togLibra.isSelected();
        double resultado;
        
        if(dolar == true){
            resultado = moeda*3;
            JOptionPane.showMessageDialog(null,"Você tem R$ " + resultado);
        }
        else{
            if(euro == true){
                resultado = moeda*4;
                JOptionPane.showMessageDialog(null,"Você tem R$ " + resultado);
            }
            else{
                resultado = moeda*5;
                JOptionPane.showMessageDialog(null, "Você tem R$ "+ resultado);
            }
        }     

    }//GEN-LAST:event_btnConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Exercicio2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverter;
    private javax.swing.ButtonGroup groupMoeda;
    private javax.swing.JLabel lbMoeda;
    private javax.swing.JLabel lbValor;
    private javax.swing.JToggleButton togDolar;
    private javax.swing.JToggleButton togEuro;
    private javax.swing.JToggleButton togLibra;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
