
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 4) Crie um programa que permita ao usuário cadastrar diversos pedidos.
 * Os dados que deverão ser armazenados dos pedidos são: data do pedido,
 * nome do cliente, cpf do cliente e valor do pedido. O programa deverá
 * exibir em um rótulo o valor total dos pedidos. 
 * @author Aluno
 * @since JFrame criado em 13/04/2018.
 */
public class Exercício4 extends javax.swing.JFrame {

    /**
     * Creates new form Exercício4
     */
    public Exercício4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDatadoPedido = new javax.swing.JLabel();
        lbNomedoCliente = new javax.swing.JLabel();
        lbCPFdoCliente = new javax.swing.JLabel();
        lbValordoProduto = new javax.swing.JLabel();
        txtDatadoPedido = new javax.swing.JTextField();
        txtNomedoCliente = new javax.swing.JTextField();
        txtCPFdoCliente = new javax.swing.JTextField();
        txtValordoProduto = new javax.swing.JTextField();
        jspProdutos = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Venda");

        lbDatadoPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbDatadoPedido.setText("Data do Pedido:");

        lbNomedoCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomedoCliente.setText("Nome do Cliente:");

        lbCPFdoCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCPFdoCliente.setText("CPF do Cliente:");

        lbValordoProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbValordoProduto.setText("Valor do Produto:");

        txtDatadoPedido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNomedoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtCPFdoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtValordoProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtProdutos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data do Pedido", "Nome do Cliente", "CPF do Cliente", "Valor do Produto", "Total dos Produtos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspProdutos.setViewportView(jtProdutos);

        btnCadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbDatadoPedido))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbCPFdoCliente)
                        .addComponent(lbNomedoCliente)
                        .addComponent(lbValordoProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomedoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValordoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105)
                .addComponent(jspProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDatadoPedido)
                            .addComponent(txtDatadoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNomedoCliente)
                            .addComponent(txtNomedoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCPFdoCliente)
                            .addComponent(txtCPFdoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValordoProduto)
                            .addComponent(txtValordoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jspProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnCadastro)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        double valordoProduto = 0;
        
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        //Declarações das variavéis
        String datadoPedido = txtDatadoPedido.getText();
        String nomedoCliente = txtNomedoCliente.getText();
        String numCPFdoCliente = txtCPFdoCliente.getText();
        double valordoProduto = Double.parseDouble(txtValordoProduto.getText());
        
        this.valordoProduto = this.valordoProduto + valordoProduto;
        //Definindo a captura dos dados da tabela.
        DefaultTableModel produtos = (DefaultTableModel) jtProdutos.getModel();
        
        //Direcionado a alocação dos dados na tabela.
        Object[] linha = new Object[5];
        
        linha[0] = datadoPedido;
        linha[1] = nomedoCliente;
        linha[2] = numCPFdoCliente;
        linha[3] = valordoProduto;
        linha[4] = (this.valordoProduto);
        
        produtos.addRow(linha);
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
               
        txtDatadoPedido.setText(null);
        txtNomedoCliente.setText(null);
        txtCPFdoCliente.setText(null);
        txtValordoProduto.setText(null);
        
        txtDatadoPedido.requestFocus();
              
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercício4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercício4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercício4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercício4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercício4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JScrollPane jspProdutos;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JLabel lbCPFdoCliente;
    private javax.swing.JLabel lbDatadoPedido;
    private javax.swing.JLabel lbNomedoCliente;
    private javax.swing.JLabel lbValordoProduto;
    private javax.swing.JTextField txtCPFdoCliente;
    private javax.swing.JTextField txtDatadoPedido;
    private javax.swing.JTextField txtNomedoCliente;
    private javax.swing.JTextField txtValordoProduto;
    // End of variables declaration//GEN-END:variables
}
