
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 2) Crie um programa que permita ao usuário cadastrar diversos produtos.
 * Os dados que deverão ser armazenados dos produtos são: código, nome,
 * quantidade, preço de custo, porcentagem de lucro e preço de venda. O preço
 * de venda deverá ser calculado com base no preço de custo e o lucro desejado
 * para cada produto.
 * @author Aluno
 */
public class Exercício2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercício2
     */
    public Exercício2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCódigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbQtde = new javax.swing.JLabel();
        lbCusto = new javax.swing.JLabel();
        lbLucro = new javax.swing.JLabel();
        txtCódigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        txtCusto = new javax.swing.JTextField();
        txtLucro = new javax.swing.JTextField();
        jspProdutos = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        btnAdiciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        lbCódigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCódigo.setText("Código:");

        lbNome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNome.setText("Nome:");

        lbQtde.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbQtde.setText("Quantidade:");

        lbCusto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCusto.setText("Custo:");

        lbLucro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbLucro.setText("Lucro (%):");

        txtCódigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCódigo.setMinimumSize(new java.awt.Dimension(6, 100));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setMinimumSize(new java.awt.Dimension(6, 100));

        txtQtde.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtQtde.setMinimumSize(new java.awt.Dimension(6, 100));

        txtCusto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCusto.setMinimumSize(new java.awt.Dimension(6, 100));

        txtLucro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLucro.setMinimumSize(new java.awt.Dimension(6, 100));

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Custo", "Lucro (%)", "Valor da Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspProdutos.setViewportView(jtProdutos);

        btnAdiciona.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdiciona.setText("Adiciona");
        btnAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbQtde)
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCódigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCusto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLucro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCódigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCusto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(btnAdiciona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jspProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCódigo)
                    .addComponent(txtCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtde)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdiciona))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCusto)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLucro)
                    .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jspProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaActionPerformed
        //Declaração das variavéis
        int código = Integer.parseInt(txtCódigo.getText());
        String nome = txtNome.getText();
        double qtdeProduto = Double.parseDouble(txtQtde.getText());
        double custo = Double.parseDouble(txtCusto.getText());
        double lucro = Double.parseDouble(txtLucro.getText());
        double vlrVenda = custo + (custo * lucro/100);
        
        //Construindo introdução de dados na tabela
        DefaultTableModel produtos = (DefaultTableModel) jtProdutos.getModel();
        
        //Criação do vetor de linha para adicionar dados na tabela
        Object[] linha = new Object[6];
        
        //Classificação dos dados em cada coluna na linha
        linha[0] = código;
        linha[1] = nome;
        linha[2] = qtdeProduto;
        linha[3] = custo;
        linha[4] = lucro;
        linha[5] = vlrVenda;
        
        produtos.addRow(linha);
        
        txtCódigo.setText(null);
        txtNome.setText(null);
        txtQtde.setText(null);
        txtCusto.setText(null);
        txtLucro.setText(null);
        
        txtCódigo.requestFocus();
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
    }//GEN-LAST:event_btnAdicionaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercício2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercício2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercício2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercício2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercício2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiciona;
    private javax.swing.JScrollPane jspProdutos;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JLabel lbCusto;
    private javax.swing.JLabel lbCódigo;
    private javax.swing.JLabel lbLucro;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbQtde;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtCódigo;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtde;
    // End of variables declaration//GEN-END:variables
}
