
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luiz.teixeira
 */
public class Aluno extends javax.swing.JFrame {

    /**
     * Creates new form Aluno
     */
    public Aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbMatrícula = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jlbAltura = new javax.swing.JLabel();
        jlbPeso = new javax.swing.JLabel();
        jlbIdade = new javax.swing.JLabel();
        jtfMatrícula = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfAltura = new javax.swing.JTextField();
        jtfPeso = new javax.swing.JTextField();
        jtfIdade = new javax.swing.JTextField();
        jbtAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aluno");

        jlbMatrícula.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jlbMatrícula.setText("Matrícula:");

        jlbNome.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jlbNome.setText("Nome:");

        jlbAltura.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jlbAltura.setText("Altura:");

        jlbPeso.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jlbPeso.setText("Peso:");

        jlbIdade.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jlbIdade.setText("Idade:");

        jtfMatrícula.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        jtfNome.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        jtfAltura.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        jtfPeso.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        jtfIdade.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        jbtAdicionar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jbtAdicionar.setText("Adicionar");
        jbtAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbMatrícula)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbNome)
                                .addComponent(jlbIdade)
                                .addComponent(jlbPeso)
                                .addComponent(jlbAltura)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMatrícula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jbtAdicionar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMatrícula)
                    .addComponent(jtfMatrícula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAltura)
                    .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPeso)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbIdade)
                    .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jbtAdicionar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAdicionarActionPerformed
        //Declaração das variavéis
        String matricula = jtfMatrícula.getText();
        String nome = jtfNome.getText();
        double altura = Double.parseDouble(jtfAltura.getText());
        double peso = Double.parseDouble(jtfPeso.getText());
        int idade = Integer.parseInt(jtfIdade.getText());
        
        //Conexão com o banco
        String usuário = "root";
        String senha = "";
        String url = "jdbc:mysql://127.0.0.1:3306/exercicio_11_05";
        
        String sql = "insert aluno values(?, ?, ?, ?, ?)";
        
        try{
            Connection conexão =
                DriverManager.getConnection(url, usuário, senha);
            
            PreparedStatement comando = 
                    conexão.prepareStatement(sql);
            
            comando.setString(1, matricula);
            comando.setString(2, nome);
            comando.setDouble(3, altura);
            comando.setDouble(4, peso);
            comando.setInt(5, idade);
            
            comando.executeUpdate();
            
            jtfMatrícula.setText(null);
            jtfNome.setText(null);
            jtfAltura.setText(null);
            jtfPeso.setText(null);
            jtfIdade.setText(null);
            
            
        }
        catch(SQLException erro){
            erro.printStackTrace();            
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar uma conexão");
        }
    }//GEN-LAST:event_jbtAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAdicionar;
    private javax.swing.JLabel jlbAltura;
    private javax.swing.JLabel jlbIdade;
    private javax.swing.JLabel jlbMatrícula;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbPeso;
    private javax.swing.JTextField jtfAltura;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfMatrícula;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPeso;
    // End of variables declaration//GEN-END:variables
}
