
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luiz.teixeira
 */
public class Carro extends javax.swing.JFrame {

    /**
     * Creates new form Carro
     */
    public Carro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbChassi = new javax.swing.JLabel();
        jlbMarca = new javax.swing.JLabel();
        jlbModelo = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jlbPlaca = new javax.swing.JLabel();
        jlbRenavam = new javax.swing.JLabel();
        jtfChassi = new javax.swing.JTextField();
        jtfMarca = new javax.swing.JTextField();
        jtfModelo = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jftfPlaca = new javax.swing.JFormattedTextField();
        jtfRenavam = new javax.swing.JTextField();
        jbtnInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbChassi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbChassi.setText("Chassi:");

        jlbMarca.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbMarca.setText("Marca:");

        jlbModelo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbModelo.setText("Modelo:");

        jlbValor.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbValor.setText("Valor:");

        jlbPlaca.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbPlaca.setText("Placa:");

        jlbRenavam.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlbRenavam.setText("Renavam:");

        jtfChassi.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfMarca.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfModelo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfValor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        try {
            jftfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfPlaca.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jtfRenavam.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jbtnInserir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtnInserir.setText("Inserir");
        jbtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbRenavam)
                    .addComponent(jlbPlaca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbChassi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfChassi)
                        .addComponent(jtfMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jtfModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jtfValor, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jftfPlaca)
                        .addComponent(jtfRenavam, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbChassi)
                    .addComponent(jtfChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMarca)
                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbModelo)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValor)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPlaca)
                    .addComponent(jftfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbRenavam)
                    .addComponent(jtfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnInserir)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInserirActionPerformed
        //Declaração de variavéis
        String chassi = jtfChassi.getText();
        String marca = jtfMarca.getText();
        String modelo = jtfModelo.getText();
        double valor = Double.parseDouble(jtfValor.getText());
        String placa = jftfPlaca.getText();
        String renavam = jtfRenavam.getText();
        
        String usuário = "root";
        String senha = "";
        String url = "jdbc:mysql://127.0.0.1:3306/exercicio_11_05";
        
        String sql = "insert carro values(?, ?, ?, ?, ?, ?)";
        
        try{
            Connection conexão =
                DriverManager.getConnection(url, usuário, senha);
            
            PreparedStatement comando = 
                    conexão.prepareStatement(sql);
            
            comando.setString(1, chassi);
            comando.setString(2, marca);
            comando.setString(3, modelo);
            comando.setDouble(4, valor);
            comando.setString(5, placa);
            comando.setString(6, renavam);
            
            comando.executeUpdate();
            
            jtfChassi.setText(null);
            jtfMarca.setText(null);
            jtfModelo.setText(null);
            jtfValor.setText(null);
            jftfPlaca.setText(null);
            jtfRenavam.setText(null);
            
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao realizar uma conexão");
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jbtnInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnInserir;
    private javax.swing.JFormattedTextField jftfPlaca;
    private javax.swing.JLabel jlbChassi;
    private javax.swing.JLabel jlbMarca;
    private javax.swing.JLabel jlbModelo;
    private javax.swing.JLabel jlbPlaca;
    private javax.swing.JLabel jlbRenavam;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTextField jtfChassi;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfRenavam;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
